kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: PowderK8s
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
#topologyManagerScope: pod
#topologyManagerPolicy: single-numa-node