apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: PowderK8s
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-downscale-stabilization: "10s"
apiServer:
  extraArgs:
    feature-gates: SCTPSupport=true
    service-node-port-range: 30000-39000
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
#---
#kind: KubeletConfiguration
#apiVersion: kubelet.config.k8s.io/v1beta1
#cgroupDriver: cgroupfs
#topologyManagerScope: pod
#topologyManagerPolicy: single-numa-node